### ISSUE TITLE
Heroku deploy COUCHDB_PORT must be a string

### ISSUE THREAD

**Issue by brabidou** [pebblecode/wfh3_backend#6]
I'm getting config var "COUCHDB_PORT" must be a string or object when I try and deploy WFH to Heroku. Looks like the app.json should have the value as string.

"COUCHDB_PORT":{
      "description":"CouchDb port",
      "value": "443"
    },

![image](https://cloud.githubusercontent.com/assets/1674538/12588954/42eea374-c429-11e5-8139-7aca49242d04.png)

**Comment by export-mike** [comment]
hey thanks for trying it out, I'll merge this now. just checked it and you're right. This must have changed since we deployed.

**Comment by export-mike** [comment]
fixed:  https://github.com/pebblecode/wfh-api/pull/7
